### ISSUE TITLE
Bundles

### ISSUE THREAD

**Issue by mrcsin** [mrcsin/zamokservis#16]
Implement bundles to reduce image redundancy 
https://gohugo.io/content-management/page-bundles/

**Comment by EvaTheSalmon** [comment]
[Markdown render hooks](https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks) also should be used to stop utilizing python compression script

The following template should be used for inserted images (keeping in mind that webp is processing in .htaccess)
```html
<picture>
    <source srcset=/img/src320/{{.Get `name`}}.jpg media="(max-width: 320px)">
    <source srcset=/img/src360/{{.Get `name`}}.jpg media="(max-width: 360px)">
    <source srcset=/img/src375/{{.Get `name`}}.jpg media="(max-width: 375px)">
    <source srcset=/img/src414/{{.Get `name`}}.jpg media="(max-width: 414px)">
    <source srcset=/img/src720/{{.Get `name`}}.jpg media="(min-width: 648px)">
    <source srcset=/img/src1080/{{.Get `name`}}.jpg media="(min-width: 972px)">
    <img class=img_block src=/img/src/{{.Get `name`}}.jpg loading="lazy" width="1400" height="900" alt="Вскрытие замков" />
</picture>

The resize script should be tolerant to condition of what's greater - width or height

**Comment by EvaTheSalmon** [comment]
Nice resize [script](https://discourse.gohugo.io/t/how-to-get-the-path-to-the-assets-directory-without-hardcoding/28217/5) reference
